# -*- coding: utf-8 -*-
"""data_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nT96V9Ta3Zqj3EAYuqi1-oRu5MfwzosB
"""

import os
import glob
from PIL import Image
from torch.utils.data import Dataset

DATA_ROOT = "/content/dataset/University-Release"

TRAIN_DRONE = f"{DATA_ROOT}/train/drone"
TRAIN_SAT = f"{DATA_ROOT}/train/google"

TEST_QUERY = f"{DATA_ROOT}/test/query_drone"
TEST_GALLERY = f"{DATA_ROOT}/test/gallery_satellite"

for path in [TRAIN_DRONE, TRAIN_SAT, TEST_QUERY, TEST_GALLERY]:
    print(path, "exists:", os.path.exists(path))

def get_first_image(folder):
    exts = ["*.jpg", "*.jpeg", "*.png", "*.JPG", "*.JPEG", "*.PNG"]
    files = []
    for ext in exts:
        files.extend(glob.glob(os.path.join(folder, ext)))
    if len(files) == 0:
        return None
    return files[0]


class UniversityPairDataset(Dataset):
    def __init__(self, drone_root, sat_root, transform=None, max_ids=50):
        self.drone_root = drone_root
        self.sat_root = sat_root
        self.transform = transform
        self.samples = []

        drone_ids = set(os.listdir(drone_root))
        sat_ids = set(os.listdir(sat_root))

        common_ids = sorted(list(drone_ids.intersection(sat_ids)))

        for building_id in common_ids:
            drone_folder = os.path.join(drone_root, building_id)
            sat_folder = os.path.join(sat_root, building_id)

            if not os.path.isdir(drone_folder) or not os.path.isdir(sat_folder):
                continue

            drone_imgs = []               #instead of picking only get_first_image() per building, use all drone images per building ID (there are multiple drone angles per building)
            for ext in ["*.jpg", "*.jpeg", "*.png", "*.JPG"]:
               drone_imgs.extend(glob.glob(os.path.join(drone_folder, ext)))

            sat_img = get_first_image(sat_folder)

            for drone_img in drone_imgs:
              if sat_img is not None:
                  self.samples.append((drone_img, sat_img, building_id))

            if len(self.samples) >= max_ids:
                break

        print("Total paired samples:", len(self.samples))

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, index):
        drone_path, sat_path, building_id = self.samples[index]

        drone_img = Image.open(drone_path).convert("RGB")
        sat_img = Image.open(sat_path).convert("RGB")

        if self.transform:
            drone_img = self.transform(drone_img)
            sat_img = self.transform(sat_img)

        return drone_img, sat_img, building_id

train_dataset = UniversityPairDataset(
    drone_root=TRAIN_DRONE,
    sat_root=TRAIN_SAT,
    transform=image_transform,
    max_ids=1000         #i gradually increased number of samples
)

sample_drone, sample_sat, sample_id = train_dataset[0]

print("Drone shape:", sample_drone.shape)
print("Satellite shape:", sample_sat.shape)
print("Building ID:", sample_id)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/transgeo2022
!ls