# -*- coding: utf-8 -*-
"""retrieval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n8zM0j589gtTb6EXXCZH8c4Z3B8INOyp
"""

class UniversityImageDataset(Dataset):
    def __init__(self, root_dir, transform=None, max_ids=100):
        self.root_dir = root_dir
        self.transform = transform
        self.samples = []

        building_ids = sorted(os.listdir(root_dir))

        for building_id in building_ids:
            folder = os.path.join(root_dir, building_id)

            if not os.path.isdir(folder):
                continue

            img_path = get_first_image(folder)

            if img_path is not None:
                self.samples.append((img_path, building_id))

            if len(self.samples) >= max_ids:
                break

        print("Total images:", len(self.samples), "from", root_dir)

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, index):
        img_path, building_id = self.samples[index]

        img = Image.open(img_path).convert("RGB")

        if self.transform:
            img = self.transform(img)

        return img, building_id, img_path

query_dataset = UniversityImageDataset(
    root_dir=TEST_QUERY,
    transform=eval_transform,
    max_ids=500  #####
)

gallery_dataset = UniversityImageDataset(
    root_dir=TEST_GALLERY,
    transform=eval_transform,
    max_ids=500
)

def extract_query_features(model, dataset, batch_size=16):
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=False, num_workers=2)

    all_features = []
    all_labels = []
    all_paths = []

    model.eval()

    with torch.no_grad():
        for imgs, labels, paths in loader:
            imgs = imgs.to(device)

            features = model.query_net(imgs)
            features = F.normalize(features, dim=1)

            all_features.append(features.cpu())
            all_labels.extend(labels)
            all_paths.extend(paths)

    all_features = torch.cat(all_features, dim=0)
    return all_features, all_labels, all_paths


def extract_gallery_features(model, dataset, batch_size=16):
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=False, num_workers=2)

    all_features = []
    all_labels = []
    all_paths = []

    model.eval()

    with torch.no_grad():
        for imgs, labels, paths in loader:
            imgs = imgs.to(device)

            features = model.reference_net(x=imgs)
            features = F.normalize(features, dim=1)

            all_features.append(features.cpu())
            all_labels.extend(labels)
            all_paths.extend(paths)

    all_features = torch.cat(all_features, dim=0)
    return all_features, all_labels, all_paths

query_features, query_labels, query_paths = extract_query_features(model, query_dataset)
gallery_features, gallery_labels, gallery_paths = extract_gallery_features(model, gallery_dataset)

print("Query features:", query_features.shape)
print("Gallery features:", gallery_features.shape)

#similarity = torch.matmul(query_features, gallery_features.T)

#top_k = 10
#scores, indices = torch.topk(similarity, k=top_k, dim=1)

#print("Top matches for first query:", indices[0])
#print("First query label:", query_labels[0])