# -*- coding: utf-8 -*-
"""XAI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ImoKT1XAi3m_BqjKFCMhUPVXU-Tftvf2
"""

# SECTION 5 - XAI, TESTING & MONITORING
# Student 5 - xai.py
#normalization
import torch
import matplotlib.pyplot as plt
import numpy as np
import torch.nn.functional as F

def unnormalize(img_tensor):
    mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
    std = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)

    img = img_tensor.cpu() * std + mean
    img = torch.clamp(img, 0, 1)

    return img.permute(1, 2, 0).numpy()

#  XAI — Saliency Map (GradCAM) + Feature Importance (Coarse Occlusion)

import torch
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
from scipy.ndimage import gaussian_filter


def unnormalize(img_tensor):
    mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
    std  = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)
    img  = img_tensor.cpu() * std + mean
    img  = torch.clamp(img, 0, 1)
    return img.permute(1, 2, 0).numpy()


def _find_vit_blocks(model):
    for attr_path in ["query_net.model", "query_net.base", "query_net"]:
        obj = model
        try:
            for part in attr_path.split("."):
                obj = getattr(obj, part)
            if hasattr(obj, "blocks"):
                return obj.blocks
        except AttributeError:
            continue
    raise RuntimeError(
        "Cannot find ViT blocks inside model.query_net. "
        "Print model.query_net to find the correct attribute path."
    )

# Find a correctly matched query index #######################3

for i in range(len(query_labels)):
    top1 = indices_faiss[i][0]
    if query_labels[i] == gallery_labels[top1]:
        print(f"query_index = {i}  →  ID: {query_labels[i]}")
        break

"""GradCAM-based saliency for TransGeo (ViT backbone).

    WHY NOT vanilla gradients:
      Vanilla gradients are computed w.r.t. the raw pixel tensor. In a ViT the
      image is first split into patches, then each patch is projected into a
      high-dimensional token, then all tokens are mixed by attention 12 times.
      By the time you backprop to the pixels, the spatial information has been
      averaged away — you get a uniform, blurry heatmap.

    HOW GRADCAM FIXES IT:
      Instead of going all the way back to the pixels, we stop at the OUTPUT of
      the last transformer block. At that point the model still has one token per
      image patch (e.g. 16×16 = 256 tokens for a 256-px image). Each token
      still "knows" which region of the image it came from. Gradients there are
      strong and spatially meaningful.

    STEPS:
      1. Hook the last ViT block to capture activations + gradients.
      2. Forward: compute cosine similarity between drone and satellite features.
      3. Backward: get gradients at the hooked layer.
      4. Weight each patch-token's activation by its mean gradient.
      5. Sum → ReLU → reshape to 2-D grid → upsample to 256×256.

    Returns
    -------
    saliency : np.ndarray shape [H, W], values in [0, 1]
"""

#1. Saliency Map — GradCAM

def generate_saliency_map(model, query_img, gallery_img, device):
    from scipy.ndimage import gaussian_filter

    model.eval()
    query_b   = query_img.unsqueeze(0).to(device)
    gallery_b = gallery_img.unsqueeze(0).to(device)

    blocks       = _find_vit_blocks(model)
    target_block = blocks[-1]
    activations, gradients = {}, {}

    def fwd_hook(module, inp, out):
        activations["v"] = out

    def bwd_hook(module, grad_in, grad_out):
        gradients["v"] = grad_out[0]

    fh = target_block.register_forward_hook(fwd_hook)
    bh = target_block.register_full_backward_hook(bwd_hook)

    with torch.no_grad():
        gallery_feat = model.reference_net(x=gallery_b)
        gallery_feat = F.normalize(gallery_feat, dim=1)

    query_feat = model.query_net(query_b)
    query_feat = F.normalize(query_feat, dim=1)
    score      = (query_feat * gallery_feat).sum()

    for p in model.parameters():
        if p.grad is not None:
            p.grad.zero_()
    score.backward()

    fh.remove()
    bh.remove()

    acts = activations["v"].detach()[:, 1:, :]
    grds = gradients["v"].detach()[:, 1:, :]

    weights   = grds.mean(dim=1, keepdim=True)
    cam       = F.relu((weights * acts).sum(dim=2))  # [1, N_patches]

    #FIX: ensure that number of tokens perfect square
    n = cam.shape[1]
    grid_side = int(n ** 0.5)
    n_keep = grid_side * grid_side
    cam = cam[:, :n_keep]                   #remove extra token
    # ────────────────────────────────────────────────

    cam = cam.reshape(1, 1, grid_side, grid_side)

    H      = query_b.shape[2]
    cam_up = F.interpolate(cam, size=(H, H), mode="bilinear", align_corners=False)
    sal    = cam_up.squeeze().cpu().numpy()
    sal    = gaussian_filter(sal, sigma=8)
    lo, hi = np.percentile(sal, 2), np.percentile(sal, 98)
    sal    = np.clip(sal, lo, hi)
    sal    = (sal - sal.min()) / (sal.max() - sal.min() + 1e-8)

    return sal

# ── 2. Feature Importance — Coarse Occlusion ─────────────────────────────────

def occlusion_feature_importance(model, query_img, gallery_img, device, grid_size=4):
    from scipy.ndimage import gaussian_filter

    model.eval()
    query_b   = query_img.unsqueeze(0).to(device)
    gallery_b = gallery_img.unsqueeze(0).to(device)

    with torch.no_grad():
        gallery_feat    = model.reference_net(x=gallery_b)
        gallery_feat    = F.normalize(gallery_feat, dim=1)
        query_feat_orig = model.query_net(query_b)
        query_feat_orig = F.normalize(query_feat_orig, dim=1)
        original_score  = torch.matmul(query_feat_orig, gallery_feat.T).item()

    _, C, H, W = query_b.shape
    patch_h    = H // grid_size
    patch_w    = W // grid_size
    imp_map    = np.zeros((grid_size, grid_size), dtype=np.float32)

    for i in range(grid_size):
        for j in range(grid_size):
            h0, h1   = i * patch_h, (i + 1) * patch_h
            w0, w1   = j * patch_w, (j + 1) * patch_w
            occluded = query_b.clone()
            local_mean = occluded[:, :, h0:h1, w0:w1].mean(dim=[2, 3], keepdim=True)
            occluded[:, :, h0:h1, w0:w1] = local_mean

            with torch.no_grad():
                occ_feat  = F.normalize(model.query_net(occluded), dim=1)
                occ_score = torch.matmul(occ_feat, gallery_feat.T).item()

            imp_map[i, j] = original_score - occ_score

    imp_t  = torch.tensor(imp_map).unsqueeze(0).unsqueeze(0)
    imp_up = F.interpolate(imp_t, size=(H, W), mode="bicubic", align_corners=False).squeeze().numpy()
    imp_up = gaussian_filter(imp_up, sigma=12)
    lo, hi = np.percentile(imp_up, 5), np.percentile(imp_up, 95)
    imp_up = np.clip(imp_up, lo, hi)
    imp_up = (imp_up - imp_up.min()) / (imp_up.max() - imp_up.min() + 1e-8)

    return imp_up, original_score

# ── RUN ───────────────────────────────────────────────────────────────────────

query_index        = i   #######################################3
top1_gallery_index = indices_faiss[query_index][0]

query_img,   query_label,   query_path   = query_dataset[query_index]
gallery_img, gallery_label, gallery_path = gallery_dataset[top1_gallery_index]

query_display = unnormalize(query_img)

# --- Saliency ---
saliency = generate_saliency_map(model, query_img, gallery_img, device)

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
axes[0].imshow(query_display)
axes[0].set_title(f"Drone Query\nTrue ID: {query_label}")
axes[0].axis("off")
axes[1].imshow(unnormalize(gallery_img))
axes[1].set_title(f"Top-1 Satellite\nPredicted ID: {gallery_label}")
axes[1].axis("off")
axes[2].imshow(query_display)
axes[2].imshow(saliency, alpha=0.55, cmap="jet")
axes[2].set_title("GradCAM Saliency Map")
axes[2].axis("off")
plt.tight_layout()
plt.show()

# --- Feature Importance ---
imp_map, original_score = occlusion_feature_importance(model, query_img, gallery_img, device, grid_size=4)

print(f"True ID: {query_label} | Predicted ID: {gallery_label} | Score: {original_score:.4f}")

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
axes[0].imshow(query_display)
axes[0].set_title(f"Drone Query\nTrue ID: {query_label}")
axes[0].axis("off")
axes[1].imshow(unnormalize(gallery_img))
axes[1].set_title(f"Top-1 Satellite\nPredicted ID: {gallery_label}")
axes[1].axis("off")
axes[2].imshow(query_display)
im = axes[2].imshow(imp_map, alpha=0.65, cmap="hot")
axes[2].set_title("Feature Importance Map")
axes[2].axis("off")
plt.colorbar(im, ax=axes[2], fraction=0.046, pad=0.04, label="Importance")
plt.tight_layout()
plt.show()